// Build-time helper: turns a binary file into a C++ source file, so the engine can carry its data
// without JUCE or any resource system.
//
//     BinToCpp <input.bin> <output.cpp> <symbol>
//
// emits   namespace petrichor::data { extern const std::uint32_t <symbol>Words[]; extern const std::size_t <symbol>Bytes; }
// The bytes are packed little-endian into 32-bit words (fewer, shorter literals than a byte array);
// readers unpack them with shifts, so the result does not depend on the target's byte order.

#include <cstdint>
#include <cstdio>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

int main (int argc, char** argv)
{
    if (argc != 4)
    {
        std::fprintf (stderr, "usage: BinToCpp <input.bin> <output.cpp> <symbol>\n");
        return 2;
    }

    std::ifstream in (argv[1], std::ios::binary);
    if (! in)
    {
        std::fprintf (stderr, "BinToCpp: cannot read %s\n", argv[1]);
        return 1;
    }
    const std::vector<unsigned char> bytes ((std::istreambuf_iterator<char> (in)), std::istreambuf_iterator<char>());
    const std::string symbol = argv[3];

    std::FILE* out = std::fopen (argv[2], "wb");
    if (out == nullptr)
    {
        std::fprintf (stderr, "BinToCpp: cannot write %s\n", argv[2]);
        return 1;
    }

    std::fprintf (out, "// Generated by Tools/BinToCpp from %s. Do not edit.\n", argv[1]);
    std::fprintf (out, "#include <cstddef>\n#include <cstdint>\n\nnamespace petrichor { namespace data {\n\n");
    std::fprintf (out, "extern const std::uint32_t %sWords[];\nextern const std::size_t %sBytes;\n\n", symbol.c_str(), symbol.c_str());
    std::fprintf (out, "const std::size_t %sBytes = %zu;\n", symbol.c_str(), bytes.size());
    std::fprintf (out, "const std::uint32_t %sWords[] = {\n", symbol.c_str());

    const std::size_t words = (bytes.size() + 3) / 4;
    for (std::size_t w = 0; w < words; ++w)
    {
        std::uint32_t v = 0;
        for (std::size_t b = 0; b < 4; ++b)
        {
            const std::size_t i = w * 4 + b;
            if (i < bytes.size())
                v |= (std::uint32_t) bytes[i] << (8 * b);
        }
        std::fprintf (out, "0x%08x,%s", (unsigned) v, (w % 12 == 11) ? "\n" : "");
    }
    if (words == 0)
        std::fprintf (out, "0");
    std::fprintf (out, "\n};\n\n} } // namespace petrichor::data\n");
    std::fclose (out);
    return 0;
}
